# Generated by Django 5.2.7 on 2026-06-18 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_message_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
